# ==========================================================
# Konfigurasi Scalability & High Availability
# ==========================================================
# Default: 1 pod
replicaCount: 1

# ==========================================================
# Konfigurasi Docker Image
# ==========================================================
image:
  repository: company-repo/company-apps
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: nexus-docker-secret

# ==========================================================
# Penamaan & Identitas (Wajib ada untuk _helpers.tpl)
# ==========================================================
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

# ==========================================================
# Konfigurasi Service (Akses dari Jaringan Luar)
# ==========================================================
service:
  type: ClusterIP
  port: 80              # Port internal service
  targetPort: 8080      # Port di dalam container
  nodePort: ""          # Dikosongkan karena sudah pakai Ingress port 30001 di level infrastruktur

# ==========================================================
# Konfigurasi NGINX INGRESS (Pintu Gerbang Utama)
# ==========================================================
ingress:
  enabled: true
  className: "nginx"
  annotations:
    # configuration limit upload memory
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    
    # ------------------------------------------------------
    # Konfigurasi Sticky Session (Wajib untuk Java/Jetty dengan 2+ Pods)
    # ------------------------------------------------------
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route-default"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific

# ==========================================================
# Environment & Resources
# ==========================================================
env: {}
  # SPRING_PROFILES_ACTIVE: "dev"

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi