replicaCount: 1

image:
  repository: company-repo/company-apps
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: nexus-docker-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

routing:
  mode: path
  domain: domain.com

tls:
  enabled: true
  secretName: platform-tls

ingress:
  enabled: true
  className: nginx
  annotations:

    nginx.ingress.kubernetes.io/proxy-body-size: "500m"

    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route-default"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"

    nginx.ingress.kubernetes.io/rewrite-target: /

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 70

healthcheck:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

canary:
  enabled: false
  weight: 20

env: {}

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi