---
# 1. ServiceAccount untuk Pod API agar dikenali oleh K8s
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-api-sa
  namespace: cicd-api-deploy

---
# 2. ClusterRole untuk memberikan akses Helm/K8s
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-api-role
rules:
  - apiGroups: ["", "apps", "networking.k8s.io", "batch", "rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]

---
# 3. Mengikat Role ke ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-api-binding
subjects:
  - kind: ServiceAccount
    name: deploy-api-sa
    namespace: cicd-api-deploy
roleRef:
  kind: ClusterRole
  name: deploy-api-role
  apiGroup: rbac.authorization.k8s.io

---
# 4. Deployment untuk menjalankan Node.js server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy-server
  namespace: cicd-api-deploy
  labels:
    app: api-deploy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deploy-server
  template:
    metadata:
      labels:
        app: api-deploy-server
    spec:
      serviceAccountName: deploy-api-sa
      containers:
        - name: api-deploy-server
          image: registry.cicd-api-deploy.svc.cluster.local:5000/deploy-api:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http

---
# 5. Service untuk mengekspos API secara internal
apiVersion: v1
kind: Service
metadata:
  name: api-deploy-service
  namespace: cicd-api-deploy
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: api-deploy-server